In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["radhe","shyam"],
    "City": ["odisha","kendrapara"],
    "Unit": [45,10],
    "Sp": [3400,5600],
    "Cp": [3000,4200]
}
df = pd.DataFrame(data)
df

    Name        City  Unit    Sp    Cp
0  radhe      odisha    45  3400  3000
1  shyam  kendrapara    10  5600  4200

In [3]:
df["Total_cost"]=df["Sp"]*df["Cp"]
df

    Name        City  Unit    Sp    Cp  Total_cost
0  radhe      odisha    45  3400  3000    10200000
1  shyam  kendrapara    10  5600  4200    23520000

In [4]:
df["Diff"]=df["Sp"]-df["Cp"]
df

    Name        City  Unit    Sp    Cp  Total_cost  Diff
0  radhe      odisha    45  3400  3000    10200000   400
1  shyam  kendrapara    10  5600  4200    23520000  1400

In [5]:
df["Prof_Loss"]=df["Diff"].apply(lambda x: "Profit" if x>0 else "Loss")
df

    Name        City  Unit    Sp    Cp  Total_cost  Diff Prof_Loss
0  radhe      odisha    45  3400  3000    10200000   400    Profit
1  shyam  kendrapara    10  5600  4200    23520000  1400    Profit

In [9]:
df["Order_Type"]=df["Unit"].apply(lambda x: "Bulk_Order" if x>20 else "Normal_Order")

In [8]:
df["Profit_Loss"] = ["profit" if x>0 else "Loss" for x in df["Diff"]]
df

,Name,City,Unit,Sp,Cp,Total_cost,Diff,Prof_Loss,Order_Type,Profit_Loss
0,radhe,odisha,45,3400,3000,10200000,400,Profit,Bulk_Order,profit
1,shyam,kendrapara,10,5600,4200,23520000,1400,Profit,Normal_Order,profit