In [26]:
import pandas as pd

In [27]:
from sklearn.preprocessing import OneHotEncoder
data = {
    'Customer': ['Rahul', 'Priya', 'Amit', 'Sneha', 'Vikas', 'Neha', 'Raj', 'Meera', 'Ankit', 'Kavya'],
    'Fruit': ['Apple', 'Orange', 'Mango', 'Apple', 'Mango', 'Banana', 'Guava', 'Mango', 'Mango', 'Grapes'],
    'Quantity': [5, 3, 10, 2, 7, 4, 6, 8, 3, 9],
    'Price_per_kg': [100, 80, 120, 100, 120, 60, 150, 120, 120, 200],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Pune', 'Mumbai'],
    'Payment_Method': ['UPI', 'Cash', 'Card', 'UPI', 'Cash', 'Card', 'UPI', 'Cash', 'Card', 'UPI'],
    'Day': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday']
}
df = pd.DataFrame(data)
df

,Customer,Fruit,Quantity,Price_per_kg,City,Payment_Method,Day
0,Rahul,Apple,5,100,Delhi,UPI,Monday
1,Priya,Orange,3,80,Mumbai,Cash,Tuesday
2,Amit,Mango,10,120,Bangalore,Card,Wednesday
3,Sneha,Apple,2,100,Delhi,UPI,Thursday
4,Vikas,Mango,7,120,Pune,Cash,Friday
5,Neha,Banana,4,60,Mumbai,Card,Saturday
6,Raj,Guava,6,150,Delhi,UPI,Sunday
7,Meera,Mango,8,120,Bangalore,Cash,Monday
8,Ankit,Mango,3,120,Pune,Card,Tuesday
9,Kavya,Grapes,9,200,Mumbai,UPI,Wednesday

In [28]:
encoder = OneHotEncoder(sparse_output = False) #here we are  creating the object
data = encoder.fit_transform(df[["Day"]]) #[[]] means dataframe
cols = encoder.get_feature_names_out()
new_data = pd.DataFrame(data,columns = cols)
new_data

,Day_Friday,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [29]:

df.drop(["Day"],axis =1, inplace = True)
df

  Customer   Fruit  Quantity  Price_per_kg       City Payment_Method
0    Rahul   Apple         5           100      Delhi            UPI
1    Priya  Orange         3            80     Mumbai           Cash
2     Amit   Mango        10           120  Bangalore           Card
3    Sneha   Apple         2           100      Delhi            UPI
4    Vikas   Mango         7           120       Pune           Cash
5     Neha  Banana         4            60     Mumbai           Card
6      Raj   Guava         6           150      Delhi            UPI
7    Meera   Mango         8           120  Bangalore           Cash
8    Ankit   Mango         3           120       Pune           Card
9    Kavya  Grapes         9           200     Mumbai            UPI

In [30]:
final_data = pd.concat([df, new_data], axis =1)
final_data

,Customer,Fruit,Quantity,Price_per_kg,City,Payment_Method,Day_Friday,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday
0,Rahul,Apple,5,100,Delhi,UPI,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,Priya,Orange,3,80,Mumbai,Cash,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Amit,Mango,10,120,Bangalore,Card,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Sneha,Apple,2,100,Delhi,UPI,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,Vikas,Mango,7,120,Pune,Cash,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Neha,Banana,4,60,Mumbai,Card,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,Raj,Guava,6,150,Delhi,UPI,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,Meera,Mango,8,120,Bangalore,Cash,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,Ankit,Mango,3,120,Pune,Card,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,Kavya,Grapes,9,200,Mumbai,UPI,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [31]:
encoder = OneHotEncoder(sparse_output = False) #here we are  creating the object
data = encoder.fit_transform(df[["Payment_Method"]]) #[[]] means dataframe
cols = encoder.get_feature_names_out()
new_data = pd.DataFrame(data,columns = cols)
new_data

   Payment_Method_Card  Payment_Method_Cash  Payment_Method_UPI
0                  0.0                  0.0                 1.0
1                  0.0                  1.0                 0.0
2                  1.0                  0.0                 0.0
3                  0.0                  0.0                 1.0
4                  0.0                  1.0                 0.0
5                  1.0                  0.0                 0.0
6                  0.0                  0.0                 1.0
7                  0.0                  1.0                 0.0
8                  1.0                  0.0                 0.0
9                  0.0                  0.0                 1.0

In [32]:

df.drop(["Payment_Method"],axis =1, inplace = True)
df

  Customer   Fruit  Quantity  Price_per_kg       City
0    Rahul   Apple         5           100      Delhi
1    Priya  Orange         3            80     Mumbai
2     Amit   Mango        10           120  Bangalore
3    Sneha   Apple         2           100      Delhi
4    Vikas   Mango         7           120       Pune
5     Neha  Banana         4            60     Mumbai
6      Raj   Guava         6           150      Delhi
7    Meera   Mango         8           120  Bangalore
8    Ankit   Mango         3           120       Pune
9    Kavya  Grapes         9           200     Mumbai

In [33]:
final_data = pd.concat([df, new_data], axis =1)
final_data

,Customer,Fruit,Quantity,Price_per_kg,City,Payment_Method_Card,Payment_Method_Cash,Payment_Method_UPI
0,Rahul,Apple,5,100,Delhi,0.0,0.0,1.0
1,Priya,Orange,3,80,Mumbai,0.0,1.0,0.0
2,Amit,Mango,10,120,Bangalore,1.0,0.0,0.0
3,Sneha,Apple,2,100,Delhi,0.0,0.0,1.0
4,Vikas,Mango,7,120,Pune,0.0,1.0,0.0
5,Neha,Banana,4,60,Mumbai,1.0,0.0,0.0
6,Raj,Guava,6,150,Delhi,0.0,0.0,1.0
7,Meera,Mango,8,120,Bangalore,0.0,1.0,0.0
8,Ankit,Mango,3,120,Pune,1.0,0.0,0.0
9,Kavya,Grapes,9,200,Mumbai,0.0,0.0,1.0

In [34]:
encoder = OneHotEncoder(sparse_output = False) #here we are  creating the object
data = encoder.fit_transform(df[["City"]]) #[[]] means dataframe
cols = encoder.get_feature_names_out()
new_data = pd.DataFrame(data,columns = cols)
new_data

   City_Bangalore  City_Delhi  City_Mumbai  City_Pune
0             0.0         1.0          0.0        0.0
1             0.0         0.0          1.0        0.0
2             1.0         0.0          0.0        0.0
3             0.0         1.0          0.0        0.0
4             0.0         0.0          0.0        1.0
5             0.0         0.0          1.0        0.0
6             0.0         1.0          0.0        0.0
7             1.0         0.0          0.0        0.0
8             0.0         0.0          0.0        1.0
9             0.0         0.0          1.0        0.0

In [21]:

df.drop(["City"],axis =1, inplace = True)
df

  Customer   Fruit  Quantity  Price_per_kg
0    Rahul   Apple         5           100
1    Priya  Orange         3            80
2     Amit   Mango        10           120
3    Sneha   Apple         2           100
4    Vikas   Mango         7           120
5     Neha  Banana         4            60
6      Raj   Guava         6           150
7    Meera   Mango         8           120
8    Ankit   Mango         3           120
9    Kavya  Grapes         9           200

In [23]:
final_data = pd.concat([df, new_data], axis =1)
final_data

,Customer,Fruit,Quantity,Price_per_kg,City_Bangalore,City_Delhi,City_Mumbai,City_Pune
0,Rahul,Apple,5,100,0.0,1.0,0.0,0.0
1,Priya,Orange,3,80,0.0,0.0,1.0,0.0
2,Amit,Mango,10,120,1.0,0.0,0.0,0.0
3,Sneha,Apple,2,100,0.0,1.0,0.0,0.0
4,Vikas,Mango,7,120,0.0,0.0,0.0,1.0
5,Neha,Banana,4,60,0.0,0.0,1.0,0.0
6,Raj,Guava,6,150,0.0,1.0,0.0,0.0
7,Meera,Mango,8,120,1.0,0.0,0.0,0.0
8,Ankit,Mango,3,120,0.0,0.0,0.0,1.0
9,Kavya,Grapes,9,200,0.0,0.0,1.0,0.0