In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
encoder = OneHotEncoder(sparse_output = False) #here we are  creating the object
data = encoder.fit_transform(df[["sex"]]) #[[]] means dataframe
cols = encoder.get_feature_names_out(["sex"])
new_data = pd.DataFrame(data,columns = cols)
new_data

      sex_female  sex_male
0            1.0       0.0
1            0.0       1.0
2            0.0       1.0
3            0.0       1.0
4            0.0       1.0
...          ...       ...
1333         0.0       1.0
1334         1.0       0.0
1335         1.0       0.0
1336         1.0       0.0
1337         1.0       0.0

[1338 rows x 2 columns]

In [19]:

df.drop(["sex", "smoker"],axis =1, inplace = True)
df

      age     bmi  children     region      charges
0      19  27.900         0  southwest  16884.92400
1      18  33.770         1  southeast   1725.55230
2      28  33.000         3  southeast   4449.46200
3      33  22.705         0  northwest  21984.47061
4      32  28.880         0  northwest   3866.85520
...   ...     ...       ...        ...          ...
1333   50  30.970         3  northwest  10600.54830
1334   18  31.920         0  northeast   2205.98080
1335   18  36.850         0  southeast   1629.83350
1336   21  25.800         0  southwest   2007.94500
1337   61  29.070         0  northwest  29141.36030

[1338 rows x 5 columns]

In [20]:
final_data = pd.concat([df, new_data], axis =1)
final_data

      age     bmi  children     region      charges  sex_female  sex_male
0      19  27.900         0  southwest  16884.92400         1.0       0.0
1      18  33.770         1  southeast   1725.55230         0.0       1.0
2      28  33.000         3  southeast   4449.46200         0.0       1.0
3      33  22.705         0  northwest  21984.47061         0.0       1.0
4      32  28.880         0  northwest   3866.85520         0.0       1.0
...   ...     ...       ...        ...          ...         ...       ...
1333   50  30.970         3  northwest  10600.54830         0.0       1.0
1334   18  31.920         0  northeast   2205.98080         1.0       0.0
1335   18  36.850         0  southeast   1629.83350         1.0       0.0
1336   21  25.800         0  southwest   2007.94500         1.0       0.0
1337   61  29.070         0  northwest  29141.36030         1.0       0.0

[1338 rows x 7 columns]